@echo off
setlocal EnableExtensions EnableDelayedExpansion

REM === Config ===
set "PY_VER=3.12.1"
set "PY_VER_NODOTS=312"
set "ARCH=amd64"
set "RUNTIME_DIR=runtime"
set "PY_DIR=%RUNTIME_DIR%\python"
set "PY_EXE=%PY_DIR%\python.exe"
set "VENV_DIR=.venv"
set "REQ=requirements.txt"
set "GETPIP_URL=https://bootstrap.pypa.io/get-pip.py"

REM Embeddable zip URL (python.org)
set "PY_ZIP=python-%PY_VER%-embed-%ARCH%.zip"
set "PY_URL=https://www.python.org/ftp/python/%PY_VER%/%PY_ZIP%"

REM === Helpers ===
where powershell >nul 2>nul
if errorlevel 1 (
  echo ERROR: PowerShell is required.
  exit /b 1
)

if not exist "%REQ%" (
  echo ERROR: %REQ% not found in repo root.
  exit /b 1
)

REM === Download embeddable Python if needed ===
if not exist "%PY_EXE%" (
  echo [1/6] Downloading Python %PY_VER% embeddable ^(%ARCH%^)...
  if not exist "%RUNTIME_DIR%" mkdir "%RUNTIME_DIR%"
  powershell -NoProfile -ExecutionPolicy Bypass -Command "$ProgressPreference='SilentlyContinue'; Invoke-WebRequest -Uri '%PY_URL%' -OutFile '%RUNTIME_DIR%\%PY_ZIP%'"
  if errorlevel 1 exit /b 1

  echo [2/6] Extracting Python to %PY_DIR%...
  if not exist "%PY_DIR%" mkdir "%PY_DIR%"
  powershell -NoProfile -ExecutionPolicy Bypass -Command "Expand-Archive -Force '%RUNTIME_DIR%\%PY_ZIP%' '%PY_DIR%'"
  if errorlevel 1 exit /b 1
) else (
  echo [1/6] Python runtime already present at %PY_EXE%
)


REM === Make embeddable behave like normal Python (enable site) ===
set "PTH_FILE=%PY_DIR%\python%PY_VER_NODOTS%._pth"
if exist "%PTH_FILE%" (
  echo [3/6] Enabling "import site" in %PTH_FILE%...
  powershell -NoProfile -ExecutionPolicy Bypass -Command "$p='%PTH_FILE%'; $c=Get-Content -LiteralPath $p; $c=$c -replace '^\s*#\s*import\s+site\s*$', 'import site'; Set-Content -Encoding ASCII -LiteralPath $p -Value $c"
  if errorlevel 1 exit /b 1
) else (
  echo [3/6] NOTE: %PTH_FILE% not found ^(ok^).
)


REM === Get pip (only if missing) ===
if not exist "%PY_DIR%\Scripts\pip.exe" (
  echo [4/6] Bootstrapping pip...
  powershell -NoProfile -ExecutionPolicy Bypass -Command "$ProgressPreference='SilentlyContinue'; Invoke-WebRequest -Uri '%GETPIP_URL%' -OutFile '%RUNTIME_DIR%\get-pip.py'"
  if errorlevel 1 exit /b 1

  "%PY_EXE%" "%RUNTIME_DIR%\get-pip.py"
  if errorlevel 1 exit /b 1
) else (
  echo [4/6] pip already present for runtime python.
)

REM === Create venv ===
if not exist "%VENV_DIR%\Scripts\python.exe" (
  echo [5/6] Creating venv in %VENV_DIR%...
  "%PY_EXE%" -m venv "%VENV_DIR%"
  if errorlevel 1 exit /b 1
) else (
  echo [5/6] venv already exists at %VENV_DIR%
)

REM === Install requirements into venv ===
echo [6/6] Installing requirements into venv...
"%VENV_DIR%\Scripts\python.exe" -m pip install --upgrade pip setuptools wheel
if errorlevel 1 exit /b 1
"%VENV_DIR%\Scripts\python.exe" -m pip install -r "%REQ%"
if errorlevel 1 exit /b 1

REM === Create run.bat (absolute paths) ===
echo Creating run.bat...

set "ROOT_DIR=%CD%"

(
  echo @echo off
  echo setlocal
  echo REM Absolute install path ^(generated by install.bat^)
  echo set "APP_ROOT=%ROOT_DIR%"
  echo REM Always run using project-local venv:
  echo "%%APP_ROOT%%\.venv\Scripts\python.exe" "%%APP_ROOT%%\launcher\launcher.py" --config "%%APP_ROOT%%\launcher\config_default.yaml" --profile "%%APP_ROOT%%\launcher\profile_default.yaml"
) > run.bat