devices:
- id: example_device_01
  driver: example.example_device
  defaults:
    duration_in_seconds: 10
    time_step: 0.1
    number_of_time_steps: 500
    noise: true
- id: filtration_cavity
  driver: kinesis.kpz101
  serial: '29250267'
  kinesis_path: C:/Program Files/Thorlabs/Kinesis
  poll_ms: 200
  simulate: false
  should_connect: true
- id: half_plate
  driver: kinesis.k10cr1
  serial: '55001297'
  kinesis_path: C:/Program Files/Thorlabs/Kinesis
  poll_ms: 200
  simulate: false
- id: mirrors
  driver: kinesis.kim101
  serial: '97101498'
  kinesis_path: C:/Program Files/Thorlabs/Kinesis
  poll_ms: 200
  simulate: false
- id: picoscope
  driver: pico_technology.ps5000a
  resolution: 14
  channels:
  - id: A
    coupling: AC
    range: 1V
    enable: true
  - id: B
    coupling: AC
    range: 1V
    enable: false
  - id: C
    coupling: AC
    range: 1V
    enable: false
  - id: D
    coupling: AC
    range: 1V
    enable: false
  trigger:
    enable: true
    source: A
    threshold_mV: 1
    direction: RISING
    delay: 0
    auto_trigger_ms: 1000
- id: chammber_pressure_gauge
  driver: other.tpg
  port: COM10
  baud: 9600
- id: AD_DDS
  driver: analog_devices.eval9959
  vid: 1110
  pid: 60965
  dll_folder: C:/Program Files (x86)/Analog Devices/AD9958_59 Evaluation Software
