devices:
- id: example_device_01
  driver: example.example_device
  should_connect: true
- id: picoscope
  driver: pico_technology.ps5000a
  resolution: 14
  channels:
  - id: A
    coupling: DC
    range: 1V
    enable: true
  - id: B
    coupling: DC
    range: 1V
    enable: false
  - id: C
    coupling: DC
    range: 1V
    enable: false
  - id: D
    coupling: DC
    range: 1V
    enable: false
  trigger:
    enable: true
    source: A
    threshold_mV: 1
    direction: RISING
    delay: 0
    auto_trigger_ms: 1000
  should_connect: true
- id: chameleon_01
  driver: red_pitaya.chameleon_mvp
  hostname: 169.254.10.10
  fpga_dir_src: null
  fpga_filename: chameleon_20260409_235513.bit
  server_dir_src: null
  overwrite_server: false
  polling_interval: 2000
  should_connect: true
