devices:
  - id: "dummy_01"
    driver: "dummy"
    defaults:
      foo: 0.42
  - id: "example_device_01"
    driver: "example_device"
    defaults:
      duration_in_seconds: 10
      time_step: 0.1
      number_of_time_steps: 500
      noise: true
  - id: "kcube"
    driver: "KPZ101"
    conn:
      serial: "29251095"         # <- your device serial
      kinesis_path: "C:/Program Files/Thorlabs/Kinesis"  # optional if KINESIS_PATH env set
      poll_ms: 200
      simulate: false
    defaults:
      voltage: 0.1
